Repository dukcode/issue-tracker, pull requests merged in 2022-06, with the labels that each got.

#10 feat: 초기 개발 환경 설정
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  fe/.eslintignore
  fe/.eslintrc.json
  fe/.gitignore
  fe/.prettierrc
  fe/package-lock.json
  fe/package.json
  fe/public/index.html
  fe/public/robots.txt
  fe/src/App.tsx
  fe/src/Component/Header/index.tsx
  fe/src/Component/Main/index.tsx
  fe/src/Styles/Normalize.tsx
  fe/src/Styles/Reset.tsx
  fe/src/Styles/index.tsx
  fe/src/Styles/theme.tsx
  fe/src/index.tsx
  fe/tsconfig.json
Labels: feat, FE

#12 feat: 로그인 페이지 생성
  fe/.eslintrc.json
  fe/package-lock.json
  fe/package.json
  fe/src/App.tsx
  fe/src/Component/Main/Login/Login.styled.tsx
  fe/src/Component/Main/Login/index.tsx
  fe/src/Component/Main/index.tsx
  fe/src/Component/NotFound/NotFound.styled.tsx
  fe/src/Component/NotFound/index.tsx
  fe/src/Img/images.d.ts
  fe/src/Img/warning.png
  fe/src/Router/index.tsx
  fe/src/Styles/Normalize.tsx
  fe/src/Styles/theme.tsx
  fe/src/Util/Icons.tsx
  fe/tsconfig.json
Labels: feat, FE, fix

#22 feat: PR 반영 ∙ 리펙토링 ∙ 로그인 구현
  fe/.gitignore
  fe/package-lock.json
  fe/package.json
  fe/src/Component/Header/index.tsx
  fe/src/Component/Home/IssueCell/IssueCell.styled.tsx
  fe/src/Component/Home/IssueCell/IssueCell.tsx
  fe/src/Component/Home/IssueCells/IssueCells.tsx
  fe/src/Component/Home/index.tsx
  fe/src/Component/Loading/Loading.styled.tsx
  fe/src/Component/Loading/index.tsx
  fe/src/Component/Login/Login.styled.tsx
  fe/src/Component/Login/index.tsx
  fe/src/Component/Main/index.tsx
  fe/src/Component/NewIssue/NewIssue.styled.tsx
  fe/src/Component/NewIssue/NewIssueContent/NewIssueContent.styled.tsx
  fe/src/Component/NewIssue/NewIssueContent/index.tsx
  fe/src/Component/NewIssue/NewIssueMain.tsx
  fe/src/Component/NewIssue/NewIssueOptions/NewIssueOptions.styled.tsx
  fe/src/Component/NewIssue/NewIssueOptions/index.tsx
  fe/src/Component/NewIssue/index.tsx
  fe/src/Component/UserImg/UserImg.styled.tsx
  fe/src/Component/UserImg/index.tsx
  fe/src/Img/user2.jpeg
  fe/src/Router/index.tsx
  fe/src/Styles/theme.tsx
  fe/src/index.tsx
Labels: feat, FE, refactor

#36 feat: 라벨 컴포넌트 생성 및 버튼, 아이콘 컴포넌트 리펙토링
  fe/src/Component/Button/Button.styled.tsx
  fe/src/Component/Button/index.tsx
  fe/src/Component/Home/FilterCategoryList/index.tsx
  fe/src/Component/Home/IssueCell/IssueCell.styled.tsx
  fe/src/Component/Home/IssueCell/index.tsx
  fe/src/Component/Home/IssueCells/IssueCells.tsx
  fe/src/Component/Home/index.tsx
  fe/src/Component/IssueHeader/IssueHeader.styled.tsx
  fe/src/Component/IssueHeader/index.tsx
  fe/src/Component/IssueOptions/IssueOptions.styled.tsx
  fe/src/Component/IssueOptions/index.tsx
  fe/src/Component/Label/Label.styled.tsx
  fe/src/Component/Label/index.tsx
  fe/src/Component/Loading/index.tsx
  fe/src/Component/NewIssue/NewIssue.styled.tsx
  fe/src/Component/NewIssue/NewIssueContent/NewIssueContent.styled.tsx
  fe/src/Component/NewIssue/index.tsx
  fe/src/Component/OptionTabs/index.tsx
  fe/src/Component/UserImg/UserImg.styled.tsx
  fe/src/Styles/Normalize.tsx
  fe/src/Styles/styled-components.d.ts
  fe/src/Styles/theme.tsx
  fe/src/Util/Icons.tsx
Labels: feat, FE, refactor

#39 refactor: 1주차 금요일 PR 반영
  fe/src/Api/labelsApi.ts
  fe/src/Api/tokenApi.ts
  fe/src/Component/IssueOptions/index.tsx
  fe/src/Component/Loading/index.tsx
  fe/src/Component/Main/index.tsx
  fe/src/Hooks/index.tsx
  fe/src/Pages/IssueList/FilterCategoryList/FilterCategory.styled.tsx
  fe/src/Pages/IssueList/FilterCategoryList/index.tsx
  fe/src/Pages/IssueList/Home.styled.tsx
  fe/src/Pages/IssueList/IssueCell/IssueCell.styled.tsx
  fe/src/Pages/IssueList/IssueCell/index.tsx
  fe/src/Pages/IssueList/index.tsx
  fe/src/Pages/Loading/Loading.styled.tsx
  fe/src/Pages/Loading/index.tsx
  fe/src/Pages/Login/Login.styled.tsx
  fe/src/Pages/Login/index.tsx
  fe/src/Pages/Main/Header/Header.styled.tsx
  fe/src/Pages/Main/Header/index.tsx
  fe/src/Pages/Main/Main.styled.tsx
  fe/src/Pages/Main/MainLoading/MainLoading.styled.tsx
  fe/src/Pages/Main/MainLoading/index.tsx
  fe/src/Pages/Main/index.tsx
  fe/src/Pages/NewIssue/NewIssue.styled.tsx
  fe/src/Pages/NewIssue/NewIssueContent/NewIssueContent.styled.tsx
  fe/src/Pages/NewIssue/NewIssueContent/index.tsx
  fe/src/Pages/NewIssue/index.tsx
  fe/src/Pages/NotFound/NotFound.styled.tsx
  fe/src/Pages/NotFound/index.tsx
  fe/src/Router/index.tsx
  fe/src/Styles/styled-components.d.ts
  fe/src/Styles/theme.tsx
Labels: FE, refactor, fix

#44 feat: 체크 박스 다중 선택 구현
  fe/src/Component/Popup/index.tsx
  fe/src/Pages/IssueList/IssueCell/index.tsx
  fe/src/Pages/IssueList/IssueListContent/IssueListContentHeader/IssueListContentHeader.styled.tsx
  fe/src/Pages/IssueList/IssueListContent/IssueListContentHeader/index.tsx
  fe/src/Pages/IssueList/IssueListContent/IssueOption/index.tsx
  fe/src/Pages/IssueList/IssueListContent/index.tsx
  fe/src/Pages/NewIssue/NewIssueContent/NewIssueContent.styled.tsx
  fe/src/Pages/NewIssue/NewIssueContent/index.tsx
Labels: feat, FE

#46 feat: 체크 박스 선택 시 상태 수정 팝업 생성
  fe/src/Api/index.ts
  fe/src/Api/issueListApi.ts
  fe/src/Api/issuesApi.ts
  fe/src/Component/Popup/Popup.styled.tsx
  fe/src/Component/Popup/PopupContent/index.tsx
  fe/src/Component/Popup/index.tsx
  fe/src/Pages/IssueList/IssueCell/index.tsx
  fe/src/Pages/IssueList/IssueListContent/IssueListContentHeader/IssueStateEditor/IssueStateEditor.styled.tsx
  fe/src/Pages/IssueList/IssueListContent/IssueListContentHeader/IssueStateEditor/index.tsx
  fe/src/Pages/IssueList/IssueListContent/IssueListContentHeader/index.tsx
  fe/src/Pages/IssueList/IssueListContent/index.tsx
  fe/src/Pages/IssueList/IssuesNotification/IssuesNotification.styled.tsx
  fe/src/Pages/IssueList/IssuesNotification/index.tsx
  fe/src/Pages/Main/MainLoading/index.tsx
Labels: feat, FE, fix

#51 feat: 레이블 목록 페이지 구현
  fe/package-lock.json
  fe/src/Api/labelsApi.ts
  fe/src/Component/Button/Button.styled.tsx
  fe/src/Component/Button/index.tsx
  fe/src/Component/Cell/Cell.styled.tsx
  fe/src/Component/Cell/index.tsx
  fe/src/Component/IssueOptions/SelectedOptions/index.tsx
  fe/src/Component/Label/AddNewLabel/AddNewLabel.styled.tsx
  fe/src/Component/Label/AddNewLabel/index.tsx
  fe/src/Component/Label/Label.styled.tsx
  fe/src/Component/Label/index.tsx
  fe/src/Component/OptionTabs/OptionsTabs.styled.tsx
  fe/src/Component/OptionTabs/index.tsx
  fe/src/Pages/IssueList/IssueCell/index.tsx
  fe/src/Pages/IssueList/IssueListContent/index.tsx
  fe/src/Pages/IssueList/mockData.ts
  fe/src/Pages/Labels/Labels.styled.tsx
  fe/src/Pages/Labels/index.tsx
  fe/src/Pages/NewIssue/NewIssueContent/NewIssueContent.styled.tsx
  fe/src/Router/index.tsx
  fe/src/Styles/theme.tsx
  fe/src/Util/Icons.tsx
Labels: feat, FE

#52 feat: issue detail 일부 생성
  .DS_Store
  fe/src/Component/Button/Button.styled.tsx
  fe/src/Component/IssueHeader/index.tsx
  fe/src/Component/Loading/index.tsx
  fe/src/Hooks/useFetch.tsx
  fe/src/Hooks/useIssues.tsx
  fe/src/Hooks/useUsers.tsx
  fe/src/Pages/IssueDetail/IssueDetail.styled.tsx
  fe/src/Pages/IssueDetail/IssueDetailHeader/IssueDetailHeader.styled.tsx
  fe/src/Pages/IssueDetail/IssueDetailHeader/IssueDetailHeaderInfo/IssueDetailHeaderInfo.styled.tsx
  fe/src/Pages/IssueDetail/IssueDetailHeader/IssueDetailHeaderInfo/index.tsx
  fe/src/Pages/IssueDetail/IssueDetailHeader/IssueDetailHeaderTitle/IssueDetailHeaderTitle.styled.tsx
  fe/src/Pages/IssueDetail/IssueDetailHeader/IssueDetailHeaderTitle/index.tsx
  fe/src/Pages/IssueDetail/IssueDetailHeader/index.tsx
  fe/src/Pages/IssueDetail/IssueDetailMain/IssueDetailMain.styled.tsx
  fe/src/Pages/IssueDetail/IssueDetailMain/index.tsx
  fe/src/Pages/IssueDetail/index.tsx
  fe/src/Pages/IssueDetail/mockData.ts
  fe/src/Pages/IssueList/IssueCell/IssueCell.styled.tsx
  fe/src/Pages/IssueList/IssueCell/index.tsx
  fe/src/Pages/IssueList/IssuesNotification/index.tsx
  fe/src/Pages/NewIssue/NewIssueHeader/NewIssueHeader.styled.tsx
  fe/src/Pages/NewIssue/NewIssueHeader/index.tsx
  fe/src/Pages/NewIssue/index.tsx
  fe/src/Router/index.tsx
  fe/src/Util/Icons.tsx
  package-lock.json
Labels: feat, FE, refactor

#55 feat: 레이블 편집 기능 구현
  fe/src/Api/labelsApi.ts
  fe/src/Component/Cell/index.tsx
  fe/src/Component/Label/LabelForm/LabelForm.styled.tsx
  fe/src/Component/Label/LabelForm/index.tsx
  fe/src/Component/OptionTabs/OptionsTabs.styled.tsx
  fe/src/Component/OptionTabs/index.tsx
  fe/src/Hooks/useUsers.tsx
  fe/src/Pages/Labels/index.tsx
  fe/src/Pages/Loading/index.tsx
  fe/src/Pages/Login/index.tsx
Labels: feat, FE

#61 refactor: 2주차 리뷰 반영
  fe/.eslintrc.json
  fe/package-lock.json
  fe/package.json
  fe/src/Component/Button/index.tsx
  fe/src/Component/Label/LabelForm/index.tsx
  fe/src/Component/OptionTabs/index.tsx
  fe/src/Component/Popup/PopupContent/index.tsx
  fe/src/Component/Popup/index.tsx
  fe/src/Component/TextButton/index.tsx
  fe/src/Component/UserImg/index.tsx
  fe/src/Hooks/useCookieUserInfo.tsx
  fe/src/Pages/IssueList/IssuesNotification/index.tsx
  fe/src/Pages/LoginLoading/LoginLoading.styled.tsx
  fe/src/Pages/LoginLoading/index.tsx
  fe/src/Router/index.tsx
  fe/src/Styles/theme.tsx
Labels: FE, refactor
